version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  deliveryBoyApp:
    image: akshayghavale/deliveryboyapp
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://deliveryBoyApp:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  endUserApp:
    image: akshayghavale/enduserapp
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://endUserApp:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local
  kafka_data:
    driver: local

networks:
  app_network:
    driver: bridge